<?php
/**
 * @file
 * Code for the ehl_site feature.
 */

include_once 'ehl_site.features.inc';

/**
 * hook_block_info
 */
function ehl_site_block_info() {
  // This example comes from node.module.
  $blocks['ehl_site_user_menu'] = array(
    'info' => t('EHL User menu'), 
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * hook_block_view
 */
function ehl_site_block_view($delta = '') {
  // This example is adapted from node.module.
  $block = array();

  switch ($delta) {
    case 'ehl_site_user_menu':
      $block['subject'] = FALSE;
      $block['content'] = ehl_site_user_menu_content();
      break;
  }
  return $block;
}

function ehl_site_user_menu_content(){
	global $user;
	$content = '';
	$content .= '<ul class="nav">';
	if($user->uid) {
		$content .= '<li>' . l('My account','user/' . $user->uid .'/posts') . '</li>';
		$content .= '<li>' . l('Logout','user/logout') . '</li>';
	} else {
		$content .= '<li>' . l('Login','user') . '</li>';
	}
	$content .= '</ul>';

	return array('#markup' => $content);
}

/**
 * hook_node_presave
 */
function ehl_site_node_presave($node) {
  if($node->type == 'post') {
    // Cute the title to make it shorter
    $node->title = substr($node->title, 0, 20);
  }
}

function ehl_site_preprocess_node(&$vars) {
  if($vars['node']->type == 'project'){
    $vars['node_url'] = url('user/' . $vars['node']->uid . '/project');
  }
}

/**
 * hook_views_pre_render
 */
function ehl_site_views_pre_render(&$view){
  if($view->name == 'my_project' && empty($view->result)){
    // if the current user is on is own project page
    global $user;
    if($user->uid == $view->args[0]){
      $view->empty['area']->options['content'] = "<h3>:( You didn't create a project. " . l('Create one', 'node/add/project') . " now.</h3>";
    }
  } 
}



/**
 * hook_form_FORM_ID_alter
 *
 * Generate the select to filter by school
 */
function ehl_site_form_views_exposed_form_alter(&$form, $form_state, $form_id) {
  $nid_options = ehl_site_universities_form_options();

  $form['univeristy'] = array (
    '#type'           => 'select',
    '#multiple'       => false,
    '#required'       => false,
    '#options'        => $nid_options,
    '#default_value'  => '',
  ); 
}


function ehl_site_universities_form_options(){
  $options = array('' => t('-- All --'));
  $result = db_query("SELECT nid, title FROM {node} WHERE type = :type ORDER BY title LIMIT 50",
    array(
      ':type' => 'school',
    )
  );
  foreach($result as $record) {
    $options[$record->nid] = $record->title;
  }
  return $options;
}

/**
 * hook_user_view
 */
function ehl_site_user_view($account){
  // Load the school slug
  $field_school = field_get_items('user', $account, 'field_school');
  if(!empty($field_school)){
    $field_school_fields_slug = field_get_items('node', $field_school[0]['entity'],'field_slug');
    $account->field_school_field_slug = $field_school_fields_slug[0]['safe_value'];
  }
}
